apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nice-rollup
  name: nice-rollup
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nice-rollup
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nice-rollup
    spec:
      containers:
        - image: gcr.io/ts-test-node/github.com/maykinayki/cloud-test
          imagePullPolicy: IfNotPresent
          name: cloud-test-1
          env:
            - name: NODE_ENV
              value: ${NODE_ENV}
            - name: CONFIG_ENV
              value: ${CONFIG_ENV}
            - name: PORT
              value: "${PORT}"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nice-rollup
  name: nice-rollup-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: nice-rollup
  ports:
    - port: 80
      protocol: TCP
      targetPort: ${PORT}
